# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
